/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGrafica;

import javax.swing.JOptionPane;
import tarea.Agenda;
import tarea.Contacto;

/**
 *
 * @author Usuario
 */
public class menuDeContactos extends javax.swing.JFrame {
    private Agenda AG;
    /**
     * Creates new form menuDeContactos
     */
    public menuDeContactos() {
        initComponents();
        listaDeAgendas.removeAllItems();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevaAgenda = new javax.swing.JButton();
        agregarContacto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        listaDeAgendas = new javax.swing.JComboBox<>();
        buscarContacto = new javax.swing.JButton();
        nombreAgenda = new javax.swing.JTextField();
        tamanio = new javax.swing.JTextField();
        nombreDeContacto = new javax.swing.JTextField();
        numeroTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevaAgenda.setText("Crear Agenda");
        nuevaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaAgendaActionPerformed(evt);
            }
        });

        agregarContacto.setText("Añadir Contacto");
        agregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarContactoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del Contacto ", "Numero de telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        listaDeAgendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeAgendasActionPerformed(evt);
            }
        });

        buscarContacto.setText("Buscar Contacto");
        buscarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarContactoActionPerformed(evt);
            }
        });

        tamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanioActionPerformed(evt);
            }
        });

        nombreDeContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreDeContactoActionPerformed(evt);
            }
        });

        numeroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nuevaAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaDeAgendas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreAgenda)
                    .addComponent(tamanio)
                    .addComponent(nombreDeContacto)
                    .addComponent(numeroTelefono))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(listaDeAgendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevaAgenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(agregarContacto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreDeContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscarContacto)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaDeAgendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDeAgendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDeAgendasActionPerformed

    private void nuevaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaAgendaActionPerformed
      String Agendita = nombreAgenda.getText();
      int tamanio1 = Integer.parseInt(tamanio.getText());
      AG = new Agenda(Agendita);
      listaDeAgendas.addItem(AG);
      
    }//GEN-LAST:event_nuevaAgendaActionPerformed

    private void tamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamanioActionPerformed

    private void buscarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarContactoActionPerformed

    private void nombreDeContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreDeContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreDeContactoActionPerformed

    private void agregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarContactoActionPerformed
       // AG = (Agenda) listaDeAgendas.getSelectedItem();
        String nuevoContacto = nombreDeContacto.getText();
        String telefono = numeroTelefono.getText();
        Contacto nuevoContacto1 = new Contacto(nuevoContacto, telefono);
        AG.aniadirContacto(nuevoContacto1);
        JOptionPane.showMessageDialog(this, "el contacto fue agregado con exito!");
    }//GEN-LAST:event_agregarContactoActionPerformed

    private void numeroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTelefonoActionPerformed
        
    }//GEN-LAST:event_numeroTelefonoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuDeContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuDeContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuDeContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuDeContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuDeContactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarContacto;
    private javax.swing.JButton buscarContacto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<Agenda> listaDeAgendas;
    private javax.swing.JTextField nombreAgenda;
    private javax.swing.JTextField nombreDeContacto;
    private javax.swing.JButton nuevaAgenda;
    private javax.swing.JTextField numeroTelefono;
    private javax.swing.JTextField tamanio;
    // End of variables declaration//GEN-END:variables
}
